# Generated by Django 5.2.5 on 2025-10-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('password', 'Password'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Select')], max_length=20)),
                ('requiredYn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('errorMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('inline', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('toasterMessage', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('options', models.ManyToManyField(related_name='form_fields', to='dynamicForm.options')),
            ],
        ),
    ]
