# Generated by Django 5.2.5 on 2025-10-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0002_uom_alter_bomsettings_defaultuom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCode', models.CharField(max_length=50, unique=True)),
                ('ProductName', models.CharField(max_length=200)),
                ('AliasName', models.CharField(blank=True, max_length=100, null=True)),
                ('PrintName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductType', models.CharField(choices=[('FG', 'Finished Good'), ('RM', 'Raw Material'), ('SF', 'Semi-Finished')], default='FG', max_length=2)),
                ('IsActive', models.BooleanField(default=True)),
                ('CompanyID', models.IntegerField(null=True)),
                ('DivisionID', models.IntegerField(null=True)),
                ('ProductGroupID', models.IntegerField(blank=True, null=True)),
                ('ProductCategoryID', models.IntegerField(blank=True, null=True)),
                ('ProductBrandID', models.IntegerField(blank=True, null=True)),
                ('UnitID', models.IntegerField(blank=True, null=True)),
                ('MinSalesRate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('MaxDiscountRate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('CostRate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('MRP', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Breadth', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Volume', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('ShortDescription', models.TextField(blank=True, null=True)),
                ('PictureName', models.CharField(blank=True, max_length=255, null=True)),
                ('ImageFileAsBase64', models.TextField(blank=True, null=True)),
                ('BatchWeightRequired', models.BooleanField(default=False)),
                ('MaintainBatchwise', models.BooleanField(default=False)),
                ('HasExpiryDate', models.BooleanField(default=False)),
                ('HasMfgDate', models.BooleanField(default=False)),
                ('DoNotMaintainInventory', models.BooleanField(default=False)),
                ('CreatedByID', models.IntegerField(blank=True, null=True)),
                ('ApprovedByID', models.IntegerField(blank=True, null=True)),
                ('ApprovedDate', models.DateTimeField(blank=True, null=True)),
                ('ModifiedDateTime', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('UOM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.uom')),
            ],
        ),
    ]
