# Generated by Django 5.2.5 on 2025-10-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MixCode', models.CharField(max_length=50, unique=True)),
                ('MixName', models.CharField(max_length=100)),
                ('Version', models.CharField(max_length=10)),
                ('Description', models.TextField(blank=True, null=True)),
                ('EffectiveFrom', models.DateField()),
                ('EffectiveTo', models.DateField(blank=True, null=True)),
                ('IsApproved', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_designs', to='manufacturing.product')),
            ],
        ),
        migrations.CreateModel(
            name='MixDesignComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('UOM', models.CharField(max_length=20)),
                ('CostRate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('TotalCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Material', models.ForeignKey(limit_choices_to={'ProductType': 'RM'}, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.product')),
                ('MixDesign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mixDesign.mixdesign')),
            ],
        ),
    ]
