# Generated by Django 5.2.5 on 2025-10-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.IntegerField()),
                ('DefaultCurrency', models.CharField(default='INR', max_length=10)),
                ('EnableVersionControl', models.BooleanField(default=True)),
                ('AutoApproveBOM', models.BooleanField(default=False)),
                ('CostingMethod', models.CharField(default='Standard', max_length=30)),
                ('RoundingPrecision', models.IntegerField(default=2)),
                ('EnableWasteTracking', models.BooleanField(default=True)),
                ('EnableBatchControl', models.BooleanField(default=True)),
                ('DefaultUOM', models.CharField(default='Nos', max_length=20)),
                ('EnableMultiLevelBOM', models.BooleanField(default=False)),
                ('LastModifiedByID', models.IntegerField(blank=True, null=True)),
                ('LastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
